// Generated by CoffeeScript 1.9.2
var chokidar, cluster, debounce, whakaruru;

whakaruru = require('whakaruru/verbose');

chokidar = require('chokidar');

debounce = require('debounce');

cluster = require('cluster');

module.exports = function(paths, cb) {
  var restart, shutdown, watch;
  whakaruru(cb);
  if (cluster.isWorker) {
    return;
  }
  restart = function() {
    return process.kill(process.pid, 'SIGHUP');
  };
  restart = debounce(restart, 500);
  console.log(process.pid + " Tāti mātaki");
  watch = chokidar.watch(paths, {
    persistent: true,
    ignoreInitial: true,
    cwd: process.cwd()
  });
  watch.on('add', function(file) {
    console.log(process.pid + " Tāpiri " + file);
    return restart();
  });
  watch.on('change', function(file) {
    console.log(process.pid + " Kōrure " + file);
    return restart();
  });
  shutdown = function() {
    console.log(process.pid + " Kati mātaki");
    return watch.close();
  };
  process.on('SIGINT', shutdown);
  return process.on('SIGTERM', shutdown);
};
